const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('public/app.js', 'utf8');
const helpers = source.slice(source.indexOf('function auditFields('), source.indexOf('function statusStyle('));
const context = vm.createContext({React:{createElement:(tag,props,...children)=>({tag,props,children})}});
vm.runInContext(helpers,context);
const text = node => node == null ? '' : typeof node !== 'object' ? String(node) : Array.isArray(node) ? node.map(text).join(' ') : text(node.children);
const snapshot = {id:2,name:'Test Manager',email:'manager@example.com',status:'Active',submissionKey:'secret-key',submissionHash:'secret-hash',password:'secret-password',remember_token:'secret-token'};
const changed = context.auditChanges(JSON.stringify(snapshot),JSON.stringify({...snapshot,status:'Inactive'}),[]);
assert.equal(changed.children[0].length,1);
assert.match(text(changed),/Status Before Active After Inactive/);
assert.doesNotMatch(text(changed),/secret|email|Test Manager/);
const nested = context.auditChanges(null,JSON.stringify({request:{id:'PO-001',submissionKey:'secret',revision:2},lines:[{productId:1,qty:9}]}),[{id:1,name:'Test product'}]);
assert.match(text(nested),/Request \/ ID/);
assert.match(text(nested),/Test product \(#1\)/);
assert.match(text(nested),/Quantity Before Not set After 9/);
assert.doesNotMatch(text(nested),/secret|Revision|\{"/);
assert.match(text(context.auditChanges(0,1,[])),/Before 0 After 1/);
assert.match(text(context.auditChanges(false,true,[])),/Before No After Yes/);
assert.match(text(context.auditChanges('Pending','Approved',[])),/Before Pending After Approved/);
assert.match(text(context.auditChanges(null,null,[])),/No displayable changes/);
assert.match(text(context.auditChanges(null,'{broken JSON',[])),/Details unavailable/);
assert.doesNotMatch(text(context.auditChanges(null,{nested:{csrf_token:'hidden',payloadHash:'hidden',qty:2}},[])),/hidden|token|Hash/);
assert.match(text(context.auditChanges({productId:1},{productId:2},[{id:1,name:'Same'},{id:2,name:'Same'}])),/#1.*#2/);
console.log('Audit formatting checks passed: readable differences, nested records, internal-field filtering, missing values, and product identity.');
